### GET request to example server
GET http://localhost:3000/users

### Send POST request with json body
POST http://localhost:3000/pets
Content-Type: application/json

{
  "name": "pepe",
  "desc": "pepe la rana",
  "img": "juan.png",
  "type": "perro",
  "status": "available"
}

### Send POST request with json body
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "luis",
  "passw": "1234"
}
